#
# OpenPBS cleanup rules
#
#Type Path                       Mode UID  GID  Time
d     /var/spool/pbs/server_logs 0755 root root 3d -
d     /var/spool/pbs/sched_logs  0755 root root 3d -
d     /var/spool/pbs/comm_logs   0755 root root 3d -
#d     /var/spool/pbs/mom_logs    0755 root root 3d -
